### ISSUE TITLE
CD 환경 구축 과정 문서화

### ISSUE THREAD

**Issue by sdrs6921** [YBE-Team-Cook/Community#11]

**Comment by laigasus** [comment]
[운영 환경](https://github.com/YBE-Team-Cook/Community/wiki/%EC%9A%B4%EC%98%81-%ED%99%98%EA%B2%BD), [프로젝트 실행](https://github.com/YBE-Team-Cook/Community/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%8B%A4%ED%96%89) 위키 작성했음
